---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to the Antelope Valley Learning Academy and I graduated in 2023. I attended The Palmdale Aerospace Academy for half of high school. English is so much easier for me than math and many students will agree with me. Math is harder for me because it involves numbers and calculation which become difficult to remember for me. I did the best in everything else, such as english, history, and science but not math class. This is because math has always been difficult for me to remember, but some different math classes are easier, for example, I prefer algebra over math. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I use an apple computer that was gifted to me on my 15th birthday. I would rate myself a 7/10 on computer knowledge because I am no hacker, but I know how to navigate basic functions. My access to the internet is pretty good and the internet only goes down sometimes, but it is manageable. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I prefer to be called by my first name, Vivian, from my classmates and instructors. My friends call me a variation of nicknames, such as viv, vivi, and v. I would like the class to call me Vivian though, only my close friends call me vivi. 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
  I want to be successful and live a happy life. I want to be rich and own a big house in the hills of Los Angeles. I'm going to be an attorney after I finish school and open up a law firm. The law subject is the greatest interest for me because I am eager to learn and continue learning the laws. I am trying to achieve my bachelor's degree in Criminal Justice and after attend law school. 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have been to Mexico a few times during my life, but no other countries yet. I want to travel the world and visit Japan, Italy, London, France, and more. I have not been in the military and I don't plan to. If I got drafted I would join the air force because I enjoyed the movie top gun and I believe flying is cool.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I took Math 115 last semester to complete my requirements for transfer. I did not know Math 116 offered  multiple transfer institutions because I was only trying to complete my requirements. I need to attain a grade of an A to maintain my GPA and have a been chance at being accepted into a great university. 

 






  




